# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Chains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('brand_name', models.CharField(verbose_name='Brand Name', max_length=100)),
                ('brand_status', models.CharField(verbose_name='Status', choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100)),
                ('brand_added_by', models.CharField(default='Admin', verbose_name='Brand Added By', max_length=100, blank=True)),
                ('brand_added_time', models.DateTimeField(auto_now_add=True, verbose_name='Brand Added Time')),
                ('brand_updated_by', models.CharField(default='Admin', verbose_name='Store Updated By', max_length=100, blank=True)),
                ('brand_updated_time', models.DateTimeField(auto_now=True, verbose_name='Store Update Time')),
            ],
            options={
                'verbose_name': 'Store Brand',
                'ordering': ['brand_name'],
                'verbose_name_plural': 'Store Brands',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Financial_Chains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('financial_brand_name', models.CharField(verbose_name='Financial Brand Name', max_length=100)),
                ('financial_brand_status', models.CharField(verbose_name='Status', choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100)),
                ('financial_brand_added_by', models.CharField(default='Admin', verbose_name='Financial Brand Added By', max_length=100, blank=True)),
                ('financial_brand_added_time', models.DateTimeField(auto_now_add=True, verbose_name='Financial Brand Added Time')),
                ('financial_brand_updated_by', models.CharField(default='Admin', verbose_name='Financial Store Updated By', max_length=100, blank=True)),
                ('financial_brand_updated_time', models.DateTimeField(auto_now=True, verbose_name='Financial Store Update Time')),
            ],
            options={
                'verbose_name': 'Store Financial Brand',
                'ordering': ['financial_brand_name'],
                'verbose_name_plural': 'Store Financial Brands',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida')], max_length=100)),
                ('locality', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Locality',
                'ordering': ['city', 'locality'],
                'verbose_name_plural': 'Localities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Payment_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('payment_type_name', models.CharField(verbose_name='Payment Type', max_length=100)),
                ('payment_type_status', models.CharField(verbose_name='Status', choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100)),
                ('payment_type_added_by', models.CharField(default='Admin', verbose_name='Payment Type Added By', max_length=100, blank=True)),
                ('payment_type_added_time', models.DateTimeField(auto_now_add=True, verbose_name='Payment Type Added Time')),
                ('payment_type_updated_by', models.CharField(default='Admin', verbose_name='Payment Type Updated By', max_length=100, blank=True)),
                ('payment_type_updated_time', models.DateTimeField(auto_now=True, verbose_name='Payment Type Update Time')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, verbose_name='ID', serialize=False)),
                ('store_name', models.CharField(help_text='Enter Store Name', verbose_name='Store Name', max_length=100)),
                ('store_address', models.CharField(verbose_name='Store Address', max_length=200)),
                ('store_city', models.CharField(default='Mumbai', verbose_name='Store City', choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida')], max_length=100)),
                ('store_country', models.CharField(default='India', verbose_name='Store Country', choices=[('India', 'India')], max_length=100)),
                ('store_pincode', models.CharField(default=201301, verbose_name='Store PINCODE', max_length=10)),
                ('store_status', models.CharField(default='Active', verbose_name='Status', choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=100)),
                ('store_type', models.CharField(default='Grocery', verbose_name='Store Type', choices=[('Fruits & Vegetables', 'Fruits & Vegetables'), ('Grocery', 'Grocery'), ('Bakery', 'Bakery'), ('Meat', 'Meat'), ('Flowers', 'Flowers')], max_length=50)),
                ('store_slug', models.SlugField(verbose_name='Store Slug', unique=True)),
                ('store_phone_number', models.CharField(verbose_name='Store Phone Number', max_length=20, blank=True)),
                ('store_order_number', models.CharField(verbose_name='Store Order Number', max_length=20, blank=True)),
                ('store_manager_number', models.CharField(verbose_name='Store Manager Number ', max_length=20, blank=True)),
                ('store_owner_number', models.CharField(verbose_name='Store Owner Number', max_length=20, blank=True)),
                ('store_owner_email', models.EmailField(null=True, verbose_name='Store Owner Email', max_length=75)),
                ('store_latitude', models.DecimalField(decimal_places=3, null=True, verbose_name='Store Latitude', blank=True, max_digits=8)),
                ('store_longitude', models.DecimalField(decimal_places=3, null=True, verbose_name='Store Longitude', blank=True, max_digits=8)),
                ('store_open_monday', models.TimeField(default='09:30', verbose_name='Store Open Time Monday')),
                ('store_close_monday', models.TimeField(default='21:30', verbose_name='Store Close Time Monday')),
                ('store_open_tuesday', models.TimeField(default='09:30', verbose_name='Store Open Time Tuesday')),
                ('store_close_tuesday', models.TimeField(default='21:30', verbose_name='Store Close Time Tuesday')),
                ('store_open_wednesday', models.TimeField(default='09:30', verbose_name='Store Open Time Wednesday')),
                ('store_close_wednesday', models.TimeField(default='21:30', verbose_name='Store Close Time Wednesday')),
                ('store_open_thursday', models.TimeField(default='09:30', verbose_name='Store Open Time Thursday')),
                ('store_close_thursday', models.TimeField(default='21:30', verbose_name='Store Close Time Thursday')),
                ('store_open_friday', models.TimeField(default='09:30', verbose_name='Store Open Time Friday')),
                ('store_close_friday', models.TimeField(default='21:30', verbose_name='Store Close Time Friday')),
                ('store_open_saturday', models.TimeField(default='09:30', verbose_name='Store Open Time Saturday')),
                ('store_close_saturday', models.TimeField(default='21:30', verbose_name='Store Close Time Saturday')),
                ('store_open_sunday', models.TimeField(default='09:30', verbose_name='Store Open Time Sunday')),
                ('store_close_sunday', models.TimeField(default='21:30', verbose_name='Store Close Time Sunday')),
                ('store_delivery_start_monday', models.TimeField(default='09:30', verbose_name='Store Delivery Start Time Monday')),
                ('store_delivery_close_monday', models.TimeField(default='21:30', verbose_name='Store Delivery Close Time Monday')),
                ('store_delivery_start_tuesday', models.TimeField(default='09:30', verbose_name='Store Delivery Start Time Tuesday')),
                ('store_delivery_close_tuesday', models.TimeField(default='21:30', verbose_name='Store Delivery Close Time Tuesday')),
                ('store_delivery_start_wednesday', models.TimeField(default='09:30', verbose_name='Store Delivery Start Time Wednesday')),
                ('store_delivery_close_wednesday', models.TimeField(default='21:30', verbose_name='Store Delivery Close Time Wednesday')),
                ('store_delivery_start_thursday', models.TimeField(default='09:30', verbose_name='Store Delivery Start Time Thursday')),
                ('store_delivery_close_thursday', models.TimeField(default='21:30', verbose_name='Store Delivery Close Time Thursday')),
                ('store_delivery_start_friday', models.TimeField(default='09:30', verbose_name='Store Delivery Start Time Friday')),
                ('store_delivery_close_friday', models.TimeField(default='21:30', verbose_name='Store Delivery Close Time Friday')),
                ('store_delivery_start_saturday', models.TimeField(default='09:30', verbose_name='Store Delivery Start Time Saturday')),
                ('store_delivery_close_saturday', models.TimeField(default='21:30', verbose_name='Store Delivery Close Time Saturday')),
                ('store_delivery_start_sunday', models.TimeField(default='09:30', verbose_name='Store Delivery Start Time Sunday')),
                ('store_delivery_close_sunday', models.TimeField(default='21:30', verbose_name='Store Delivery Close Time Sunday')),
                ('store_sales_rep', models.CharField(verbose_name='Sales Representative', max_length=100, blank=True)),
                ('store_account_manager', models.CharField(verbose_name='Account Manager', max_length=100, blank=True)),
                ('store_delivery_area_primary', models.PositiveSmallIntegerField(default=2, verbose_name='Primary Delivery Radius KM:')),
                ('store_min_order_primary', models.PositiveSmallIntegerField(default=200, verbose_name='Minimum Order Primary Radius')),
                ('store_delivery_area_secondary', models.PositiveSmallIntegerField(default=5, verbose_name='Secondary Delivery Radius')),
                ('store_min_order_secondary', models.PositiveSmallIntegerField(default=500, verbose_name='Minimum Order Secondary Radius')),
                ('store_payment_cycle', models.PositiveSmallIntegerField(null=True, verbose_name='Payment Cycle', blank=True)),
                ('store_bank_account', models.CharField(verbose_name='Bank Account', max_length=100, blank=True)),
                ('store_display_order', models.SmallIntegerField(help_text='Please give a order number. Stores displayed as per this sorting ', verbose_name='Display Order')),
                ('store_added_by', models.CharField(default='Admin', verbose_name='Store Added By', max_length=100, blank=True)),
                ('store_added_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Store Added Time')),
                ('store_updated_by', models.CharField(default='Admin', verbose_name='Store Updated By', max_length=100, blank=True)),
                ('store_updated_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Store Update Time')),
                ('store_associated_brand_chain', models.ForeignKey(blank=True, to='store.Brand_Chains', null=True, verbose_name='Associated Brand')),
                ('store_associated_financial_chain', models.ForeignKey(blank=True, to='store.Financial_Chains', null=True, verbose_name='Associated Brand')),
                ('store_locality', models.ForeignKey(verbose_name='Store Locality', to='store.Locality')),
                ('store_payment_methods', models.ManyToManyField(null=True, verbose_name='Payment Types', to='store.Payment_Types')),
            ],
            options={
                'ordering': ['store_locality'],
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('store_name', 'store_locality', 'store_city')]),
        ),
        migrations.AlterIndexTogether(
            name='store',
            index_together=set([('store_locality', 'store_city')]),
        ),
    ]
