# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Chains',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('brand_name', models.CharField(verbose_name='Brand Name', max_length=100)),
                ('brand_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], verbose_name='Status', max_length=100)),
                ('brand_added_by', models.CharField(verbose_name='Brand Added By', blank=True, max_length=100, default='Admin')),
                ('brand_added_time', models.DateTimeField(auto_now_add=True, verbose_name='Brand Added Time')),
                ('brand_updated_by', models.CharField(verbose_name='Store Updated By', blank=True, max_length=100, default='Admin')),
                ('brand_updated_time', models.DateTimeField(auto_now=True, verbose_name='Store Update Time')),
            ],
            options={
                'ordering': ['brand_name'],
                'verbose_name': 'Store Brand',
                'verbose_name_plural': 'Store Brands',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Financial_Chains',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('financial_brand_name', models.CharField(verbose_name='Financial Brand Name', max_length=100)),
                ('financial_brand_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], verbose_name='Status', max_length=100)),
                ('financial_brand_added_by', models.CharField(verbose_name='Financial Brand Added By', blank=True, max_length=100, default='Admin')),
                ('financial_brand_added_time', models.DateTimeField(auto_now_add=True, verbose_name='Financial Brand Added Time')),
                ('financial_brand_updated_by', models.CharField(verbose_name='Financial Store Updated By', blank=True, max_length=100, default='Admin')),
                ('financial_brand_updated_time', models.DateTimeField(auto_now=True, verbose_name='Financial Store Update Time')),
            ],
            options={
                'ordering': ['financial_brand_name'],
                'verbose_name': 'Store Financial Brand',
                'verbose_name_plural': 'Store Financial Brands',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Delhi', 'Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida')], max_length=100)),
                ('locality', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['city', 'locality'],
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Localities',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Payment_Types',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('payment_type_name', models.CharField(verbose_name='Payment Type', max_length=100)),
                ('payment_type_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], verbose_name='Status', max_length=100)),
                ('payment_type_added_by', models.CharField(verbose_name='Payment Type Added By', blank=True, max_length=100, default='Admin')),
                ('payment_type_added_time', models.DateTimeField(auto_now_add=True, verbose_name='Payment Type Added Time')),
                ('payment_type_updated_by', models.CharField(verbose_name='Payment Type Updated By', blank=True, max_length=100, default='Admin')),
                ('payment_type_updated_time', models.DateTimeField(auto_now=True, verbose_name='Payment Type Update Time')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID', primary_key=True)),
                ('store_name', models.CharField(help_text='Enter Store Name', verbose_name='Store Name', max_length=100)),
                ('store_address', models.CharField(verbose_name='Store Address', max_length=200)),
                ('store_country', models.CharField(choices=[('India', 'India')], verbose_name='Store Country', default='India', max_length=100)),
                ('store_pincode', models.CharField(verbose_name='Store PINCODE', default=201301, max_length=10)),
                ('store_status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], verbose_name='Status', default='Active', max_length=100)),
                ('store_type', models.CharField(choices=[('Fruits & Vegetables', 'Fruits & Vegetables'), ('Grocery', 'Grocery'), ('Bakery', 'Bakery'), ('Meat', 'Meat'), ('Flowers', 'Flowers')], verbose_name='Store Type', default='Grocery', max_length=50)),
                ('store_phone_number', models.CharField(verbose_name='Store Phone Number', blank=True, max_length=20)),
                ('store_order_number', models.CharField(verbose_name='Store Order Number', blank=True, max_length=20)),
                ('store_manager_number', models.CharField(verbose_name='Store Manager Number ', blank=True, max_length=20)),
                ('store_owner_number', models.CharField(verbose_name='Store Owner Number', blank=True, max_length=20)),
                ('store_owner_email', models.EmailField(verbose_name='Store Owner Email', blank=True, max_length=75)),
                ('store_latitude', models.DecimalField(null=True, verbose_name='Store Latitude', max_digits=8, blank=True, decimal_places=3)),
                ('store_longitude', models.DecimalField(null=True, verbose_name='Store Longitude', max_digits=8, blank=True, decimal_places=3)),
                ('store_open_monday', models.TimeField(verbose_name='Monday', default='09:30')),
                ('store_close_monday', models.TimeField(verbose_name='SMonday', default='21:30')),
                ('store_open_tuesday', models.TimeField(verbose_name='Tuesday', default='09:30')),
                ('store_close_tuesday', models.TimeField(verbose_name='Tuesday', default='21:30')),
                ('store_open_wednesday', models.TimeField(verbose_name='Wednesday', default='09:30')),
                ('store_close_wednesday', models.TimeField(verbose_name='Wednesday', default='21:30')),
                ('store_open_thursday', models.TimeField(verbose_name='Thursday', default='09:30')),
                ('store_close_thursday', models.TimeField(verbose_name='Thursday', default='21:30')),
                ('store_open_friday', models.TimeField(verbose_name='Friday', default='09:30')),
                ('store_close_friday', models.TimeField(verbose_name='Friday', default='21:30')),
                ('store_open_saturday', models.TimeField(verbose_name='Saturday', default='09:30')),
                ('store_close_saturday', models.TimeField(verbose_name='Saturday', default='21:30')),
                ('store_open_sunday', models.TimeField(verbose_name='Sunday', default='09:30')),
                ('store_close_sunday', models.TimeField(verbose_name='Sunday', default='21:30')),
                ('store_delivery_start_monday', models.TimeField(verbose_name='Monday', default='09:30')),
                ('store_delivery_close_monday', models.TimeField(verbose_name='Monday', default='21:30')),
                ('store_delivery_start_tuesday', models.TimeField(verbose_name='Tuesday', default='09:30')),
                ('store_delivery_close_tuesday', models.TimeField(verbose_name='Tuesday', default='21:30')),
                ('store_delivery_start_wednesday', models.TimeField(verbose_name='Wednesday', default='09:30')),
                ('store_delivery_close_wednesday', models.TimeField(verbose_name='Wednesday', default='21:30')),
                ('store_delivery_start_thursday', models.TimeField(verbose_name='Thursday', default='09:30')),
                ('store_delivery_close_thursday', models.TimeField(verbose_name='Thursday', default='21:30')),
                ('store_delivery_start_friday', models.TimeField(verbose_name='Friday', default='09:30')),
                ('store_delivery_close_friday', models.TimeField(verbose_name='Friday', default='21:30')),
                ('store_delivery_start_saturday', models.TimeField(verbose_name='Saturday', default='09:30')),
                ('store_delivery_close_saturday', models.TimeField(verbose_name='Saturday', default='21:30')),
                ('store_delivery_start_sunday', models.TimeField(verbose_name='Sunday', default='09:30')),
                ('store_delivery_close_sunday', models.TimeField(verbose_name='Sunday', default='21:30')),
                ('store_sales_rep', models.CharField(verbose_name='Sales Representative', blank=True, max_length=100)),
                ('store_account_manager', models.CharField(verbose_name='Account Manager', blank=True, max_length=100)),
                ('store_delivery_area_primary', models.PositiveSmallIntegerField(verbose_name='Primary Delivery Radius KM:', default=2)),
                ('store_min_order_primary', models.PositiveSmallIntegerField(verbose_name='Minimum Order Primary Radius', default=200)),
                ('store_delivery_area_secondary', models.PositiveSmallIntegerField(verbose_name='Secondary Delivery Radius', default=5)),
                ('store_min_order_secondary', models.PositiveSmallIntegerField(verbose_name='Minimum Order Secondary Radius', default=500)),
                ('store_payment_cycle', models.PositiveSmallIntegerField(null=True, verbose_name='Payment Cycle', blank=True)),
                ('store_bank_account', models.CharField(verbose_name='Bank Account', blank=True, max_length=100)),
                ('store_display_order', models.SmallIntegerField(help_text='Please give a order number. Stores displayed as per this sorting ', verbose_name='Display Order')),
                ('store_added_by', models.CharField(verbose_name='Store Added By', blank=True, max_length=100, default='Admin')),
                ('store_added_time', models.DateTimeField(null=True, verbose_name='Store Added Time', auto_now_add=True)),
                ('store_updated_by', models.CharField(verbose_name='Store Updated By', blank=True, max_length=100, default='Admin')),
                ('store_updated_time', models.DateTimeField(null=True, verbose_name='Store Update Time', auto_now=True)),
                ('store_associated_brand_chain', models.ForeignKey(verbose_name='Associated Brand', to='store.Brand_Chains', null=True, blank=True)),
                ('store_associated_financial_chain', models.ForeignKey(verbose_name='Associated Brand', to='store.Financial_Chains', null=True, blank=True)),
                ('store_locality_city', models.ForeignKey(verbose_name='Store Locality & City', to='store.Locality')),
                ('store_payment_methods', models.ManyToManyField(null=True, verbose_name='Payment Types', to='store.Payment_Types')),
            ],
            options={
                'ordering': ['store_locality_city__city', 'store_locality_city__locality'],
                'verbose_name': 'Store',
                'verbose_name_plural': 'Stores',
            },
            bases=(models.Model,),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together=set([('store_name', 'store_locality_city')]),
        ),
    ]
